### ISSUE TITLE
wip/migrate_1.3 - ReferenceError: Meteor is not defined (chimp error)

### ISSUE THREAD

**Issue by lucidprogrammer** [xolvio/automated-testing-best-practices#23]
Using the following branch
git clone -b wip/migrate_1.3 --single-branch https://github.com/xolvio/automated-testing-best-practices.git

--I am getting the following error when I run npm start on windows----

C:\Users\projects\automated-testing-best-practices>npm start

> @ start C:\Users\projects\automated-testing-best-practices
> node .scripts/start.js

[[[[[ C:\Users\projects\automated-testing-best-practices\src ]]]]]

=> Started proxy.
=> Started MongoDB.
=> Started your app.

=> App running at: http://localhost:3000
   Type Control-C twice to stop.

[chimp] Watching features with tagged with @focus

[chimp] Running...

[chimp] domain scenarios...
C:\Users\projects\automated-testing-best-practices\src\imports\domain\services\bank-service\iso.js:3
module.exports = Meteor.isServer ? require('./server/bank-service') : require('./client/bank-service');
                 ^

ReferenceError: Meteor is not defined
    at Object.<anonymous> (iso.js:1:18)
    at Module._compile (module.js:399:26)
    at loader (C:\Users\projects\automated-testing-best-practices.scripts\node_modules\babel-register\lib\node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js](C:Usersprojectsautomated-testing-best-practices.scriptsnode_modulesbabel-registerlibnode.js:138:7)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)
    at Object.<anonymous> (C:\Users\projects\automated-testing-best-practices\src\imports\domain\services\bank-service\index.js:27:12)
    at Module._compile (module.js:399:26)
    at loader (C:\Users\projects\automated-testing-best-practices.scripts\node_modules\babel-register\lib\node.js:128:5)
    at Object.require.extensions.(anonymous function) [as .js](C:Usersprojectsautomated-testing-best-practices.scriptsnode_modulesbabel-registerlibnode.js:138:7)
    at Module.load (module.js:345:32)
    at Function.Module._load (module.js:302:12)
    at Module.require (module.js:355:17)
    at require (internal/module.js:13:17)

---

changes to **automated-testing-best-practices.scripts\node_modules\chimp\chimp.js**
`replace process.env.PWD with process.env.PWD?process.env.PWD:process.cwd()`

> to support windows. great if it is fixed upstream in chimp

---

changes to wallaby_server.js
(this works perfectly for me now)

```
if(process.platform === 'win32'){
    //which is the meteor release
    var releaseFile = path.join(wallaby.localProjectDir,'src','.meteor','release');
    var meteorRelease = fs.readFileSync(releaseFile).toString().trim().replace('METEOR@','');
    meteorRelease = '1.1.'+ [meteorRelease.split('-')[0].split('.').join('') , meteorRelease.split('-')[1] ].join('-');
    require('shelljs/global');
    var meteorInstallation = which('meteor').replace('meteor.bat','');
    console.log(meteorInstallation)
    runner = path.join(meteorInstallation,'packages','meteor-tool',meteorRelease,'mt-os.windows.x86_32','dev_bundle','bin','node.exe');
    console.log(runner)
  } else {
  runner  = path.resolve(process.env.HOME, '.nvm/v0.10.40/bin/node')
  }
```

---

```
env: {
      type: 'node',
      runner:runner
    }
```

as fibers don't work, used the following 
copied meteorInstallation + \packages\velocity_meteor-tool\1.1.10_2\mt-os.windows.x86_32\dev_bundle\server-lib\node_modules\fibers\bin\win32-ia32-v8-3.14 to 
C:\Users\projects\automated-testing-best-practices\node_modules\fibers\bin

> ## also inside bootstrap, var fs is to be defined.
> 
> Great if you can help me with the chimp error outlined above. Tks

**Comment by lucidprogrammer** [comment]
one more stab at it, following fixed it, not the elegant way though
module.exports = ((typeof Meteor === 'undefined') || Meteor.isServer) ?
   require('./server/bank-service') :
   require('./client/bank-service');
