### ISSUE TITLE
wallaby.js with meteor 1.6

### ISSUE THREAD

**Issue by louismarie** [xolvio/automated-testing-best-practices#73]
I'm trying to get wallaby working with meteor 1.6

I am using this configuration file : 
https://github.com/mindhivenz/wallaby-meteor-config

It was working with meteor 1.5 but now it is broken after a "meteor update"

This is the wallaby error I have :
`Wed, 08 Nov 2017 09:58:16 GMT wallaby:project Error: Failed to run compilers on src/packages/npm-container/index.js, TypeError: Cannot read property 'helpers' of undefined
  at _default (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-plugin-transform-runtime/lib/index.js:20:24)
  at Function.memoisePluginContainer (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:113:13)
  at Function.normalisePlugin (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:146:32)
  at /Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:184:30
  at Array.map (<anonymous>:null:null)
  at Function.normalisePlugins (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
  at OptionManager.mergeOptions (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
  at /Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:265:14
  at /Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:323:22
  at Array.map (<anonymous>:null:null)
  at OptionManager.resolvePresets (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:275:20)
  at OptionManager.mergePresets (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:264:10)
  at OptionManager.mergeOptions (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:249:14)
  at OptionManager.init (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
  at File.initOptions (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/index.js:212:65)
  at new File (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/file/index.js:135:24)
  at Pipeline.transform (/Users/user/.meteor/packages/meteor-tool/.1.6.0.130umtl.ycp7++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/lib/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at emitTwo (events.js:125:13)
  at process.emit (events.js:213:7)
  at emit (internal/child_process.js:774:12)
  at _combinedTickCallback (internal/process/next_tick.js:141:11)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
  at /Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/server.js:18:586
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
  at b._processFile (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/server.js:18:3438)
  at /Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/server.js:17:31471
  at _combinedTickCallback (internal/process/next_tick.js:131:7)
  at process._tickCallback (internal/process/next_tick.js:180:9)
From previous event:
  at b._writeFileChanges (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/server.js:17:31507)
  at /Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/server.js:17:21106
  at baseFor (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/node_modules/lodash/index.js:1971:13)
  at baseForOwn (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/node_modules/lodash/index.js:2025:14)
  at baseEach (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/node_modules/lodash/index.js:1814:16)
  at Function.forEach (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/node_modules/lodash/index.js:5701:11)
  at b._processChangedQueue (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/server.js:17:20233)
  at Timeout._onTimeout (/Users/user/Library/Caches/WebStorm2017.2/wallaby/wallaby/server.js:17:14138)
  at ontimeout (timers.js:469:11)
  at tryOnTimeout (timers.js:304:5)
  at Timer.listOnTimeout (timers.js:264:5)`

Meteor Changelog might help :
http://docs.meteor.com/changelog.html#v1620171030

Any ideas ?

EDIT: I have simple js meteor code in index.js and if I erase the file, the same error is thrown for the next js file. So I think it is not related to my code.

**Comment by formspoint** [comment]
Did you ever get this working?

**Comment by louismarie** [comment]
Yes it works.
This is the complete [config file](https://gist.github.com/louismarie/06c08692e23487506cf6aa08c4ae491b)

**Comment by formspoint** [comment]
Thanks.  But it's still now working, even with your config.  

* I installed the Wallaby plugin in VisualStudio Code
* ran the following command on my project:
```yarn add --dev @mindhive/wallaby-meteor-config```
* created the wallaby.js configuration file in the root directory of my project, with your config
* created a \src\imports folder
* created a temp.spec.js file under \src\imports folder
* the temp.spec.js file simply looks like this:
```
it('this is a test', () => {
  const dev = 134;
  console.log(dev);
});
```

**Comment by louismarie** [comment]
I just created [meteorwallaby repository](https://github.com/louismarie/meteorwallaby) with a sample meteor app, wallaby integration and a sample test.
Just works with wallaby and WebStorm.
Please let me know if it works with VisualStudio Code.
